const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 399,
    originalPrice: 499,
    rating: 4.5,
    category: "Classic",
    image:
      "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=700&q=85",
    description:
      "A dazzling portrait of the Jazz Age and a haunting meditation on ambition, love, and the American dream.",
    publisher: "Scribner",
    publicationDate: "April 10, 1925",
    isbn: "978-0743273565",
    pages: 180,
    language: "English",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    category: "Self Development",
    image: "images/atomic-habits.svg",
    description:
      "An easy and proven way to build good habits and break bad ones through tiny, remarkable changes.",
    publisher: "Avery",
    publicationDate: "October 16, 2018",
    isbn: "978-0735211292",
    pages: 320,
    language: "English",
  },
  {
    id: 3,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    category: "Fiction",
    image:
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=700&q=85",
    description:
      "Paulo Coelho’s inspiring tale reminds us to listen to our hearts and follow our dreams.",
    publisher: "HarperOne",
    publicationDate: "May 1, 1993",
    isbn: "978-0062315007",
    pages: 208,
    language: "English",
  },
  {
    id: 4,
    title: "Harry Potter and the Sorcerer’s Stone",
    author: "J.K. Rowling",
    price: 599,
    originalPrice: 799,
    rating: 4.9,
    category: "Fantasy",
    image:
      "https://images.unsplash.com/photo-1618666012174-83b441c0bc76?auto=format&fit=crop&w=700&q=85",
    description:
      "The first magical adventure of the boy wizard Harry Potter at Hogwarts School of Witchcraft and Wizardry.",
    publisher: "Bloomsbury",
    publicationDate: "June 26, 1997",
    isbn: "978-0590353427",
    pages: 309,
    language: "English",
  },
  {
    id: 5,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 449,
    originalPrice: 599,
    rating: 4.6,
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=700&q=85",
    description:
      "What the rich teach their kids about money that the poor and middle class do not.",
    publisher: "Plata Publishing",
    publicationDate: "April 1, 1997",
    isbn: "978-1612680194",
    pages: 336,
    language: "English",
  },
  {
    id: 6,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 499,
    originalPrice: 699,
    rating: 4.7,
    category: "Business",
    image:
      "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=700&q=85",
    description:
      "Timeless lessons on wealth, greed, and happiness, told through twenty short stories.",
    publisher: "Harriman House",
    publicationDate: "September 8, 2020",
    isbn: "978-0857197689",
    pages: 256,
    language: "English",
  },
  {
    id: 7,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 299,
    originalPrice: 399,
    rating: 4.7,
    category: "Romance",
    image: "images/pride-and-prejudice.svg",
    description:
      "A beloved comedy of manners about first impressions, family, and the surprising nature of love.",
    publisher: "Penguin Classics",
    publicationDate: "January 28, 1813",
    isbn: "978-0141439518",
    pages: 432,
    language: "English",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 549,
    originalPrice: 699,
    rating: 4.8,
    category: "Fantasy",
    image:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=700&q=85",
    description:
      "Bilbo Baggins leaves his comfortable hobbit-hole for a journey filled with dragons, dwarves, and wonder.",
    publisher: "Mariner Books",
    publicationDate: "September 21, 1937",
    isbn: "978-0547928227",
    pages: 310,
    language: "English",
  },
  {
    id: 9,
    title: "And Then There Were None",
    author: "Agatha Christie",
    price: 379,
    originalPrice: 499,
    rating: 4.6,
    category: "Mystery",
    image:
      "https://images.unsplash.com/photo-1529590003495-b2646e2718bf?auto=format&fit=crop&w=700&q=85",
    description:
      "Ten strangers are lured to an isolated island, where an unseen host begins to judge them one by one.",
    publisher: "William Morrow",
    publicationDate: "November 6, 1939",
    isbn: "978-0062073488",
    pages: 272,
    language: "English",
  },
  {
    id: 10,
    title: "Dune",
    author: "Frank Herbert",
    price: 599,
    originalPrice: 799,
    rating: 4.7,
    category: "Science Fiction",
    image:
      "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=700&q=85",
    description:
      "An epic tale of politics, ecology, and destiny on the desert planet Arrakis.",
    publisher: "Ace",
    publicationDate: "August 1, 1965",
    isbn: "978-0441172719",
    pages: 688,
    language: "English",
  },
  {
    id: 11,
    title: "Educated",
    author: "Tara Westover",
    price: 479,
    originalPrice: 649,
    rating: 4.7,
    category: "Biography",
    image:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=700&q=85",
    description:
      "A memoir about education, family, and the remarkable journey from isolation to self-invention.",
    publisher: "Random House",
    publicationDate: "February 20, 2018",
    isbn: "978-0399590504",
    pages: 352,
    language: "English",
  },
  {
    id: 12,
    title: "The Art of Learning",
    author: "Josh Waitzkin",
    price: 429,
    originalPrice: 599,
    rating: 4.5,
    category: "Academic",
    image:
      "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=700&q=85",
    description:
      "A journey into the inner world of high-level performance and the art of mastering new skills.",
    publisher: "Free Press",
    publicationDate: "May 13, 2008",
    isbn: "978-0743277464",
    pages: 288,
    language: "English",
  },
];
